name: Pull request
on: 
  pull_request: 
    branches: 
      - '**'

jobs:
  build_container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build containers
        run: docker compose build