name: Pull request
on: 
  pull_request: 
    branches: 
      - '**'

jobs:
  build_container:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/maybeanerd/magibot-main-pr

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build containers
        run: docker compose build