name: Release to production

on: 
  release:

jobs:
  container:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # TODO copy from dev release, or use shared action for it?